tests: notification: skip relevant tests when sessiond start fails
For unknown reasons the sessiond starts in this test were done without
tap output making it less obvious what was the source problem when I had
to debug test failures.

Add tap output to all start and stop of the sessiond and skip the
relevant tests when the sessiond fails to start.

Also some minor shellcheck fixes while we are here.

Change-Id: Ib869af99310401cca0f6a970d1ac42b33d9750b7
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>

diff --git a/tests/regression/tools/notification/test_notification_ust_buffer_usage b/tests/regression/tools/notification/test_notification_ust_buffer_usage
--- a/tests/regression/tools/notification/test_notification_ust_buffer_usage
+++ b/tests/regression/tools/notification/test_notification_ust_buffer_usage
@@ -85,11 +85,15 @@ function test_buffer_usage_notification
 	diag "Test done"
 }
 
+LTTNG_SESSIOND_ENV_VARS="LTTNG_TESTPOINT_ENABLE=1 CONSUMER_PAUSE_PIPE_PATH=${TESTPOINT_PIPE_PATH} LD_PRELOAD=${TESTPOINT}"
+if ! start_lttng_sessiond_notap; then
+	plan_tests 1
+	fail "Failed to start sessiond"
+	exit
+fi
+
 # Avoid spurious messages about exiting before the test output anything on cleanup
 tap_disable
-
-LTTNG_SESSIOND_ENV_VARS="LTTNG_TESTPOINT_ENABLE=1 CONSUMER_PAUSE_PIPE_PATH=${TESTPOINT_PIPE_PATH} LD_PRELOAD=${TESTPOINT}"
-start_lttng_sessiond_notap
 
 test_buffer_usage_notification
 
