fixup! Tests: Add callstack contexts tests

diff --git a/tests/regression/kernel/test_callstack b/tests/regression/kernel/test_callstack
--- a/tests/regression/kernel/test_callstack
+++ b/tests/regression/kernel/test_callstack
@@ -19,8 +19,9 @@ TEST_DESC="Kernel tracer - Callstack context"
 
 CURDIR=$(dirname "$0")/
 TESTDIR=$CURDIR/../..
-NUM_TESTS=18
-TEST_APP="$TESTDIR/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack"
+NUM_TESTS=11
+TEST_APP_USERSPACE="$TESTDIR/utils/testapp/gen-syscall-events-callstack/gen-syscall-events-callstack"
+TEST_APP_KERNELSPACE="$TESTDIR/utils/testapp/gen-syscall-events/gen-syscall-events"
 PARSE_CALLSTACK="$TESTDIR/utils/parse-callstack.py"
 
 SESSION_NAME="callstack"
@@ -30,17 +31,18 @@ source "$TESTDIR/utils/utils.sh"
 
 function lttng_untrack_all()
 {
-	lttng untrack -s "$SESSION_NAME" --all --pid -k > /dev/null
+	lttng_untrack 0 "-s $SESSION_NAME --all --pid -k"
 }
 
 function lttng_track_pid()
 {
 	local PID=$1
-	lttng track -s "$SESSION_NAME" -k --pid="$PID" > /dev/null
+	lttng_track 0 "-s $SESSION_NAME -k --pid=$PID"
 }
 
 function run_workload()
 {
+	local TEST_APP=$1
 	local start_file_sync
 	start_file_sync=$(mktemp -u)
 
@@ -53,14 +55,14 @@ function run_workload()
 	start_lttng_tracing_ok
 
 	# Create start file to launch the execution of the syscall call by the
-	# test app
+	# test app.
 	touch "$start_file_sync"
 
 	wait $PID
 
 	stop_lttng_tracing_ok
 
-	# Clean up the synchronization file
+	# Clean up the synchronization file.
 	rm -f "$start_file_sync"
 }
 
@@ -78,11 +80,11 @@ function test_user_callstack()
 	lttng_enable_kernel_syscall_ok "$SESSION_NAME" "$EVENT_NAME" "$CHANNEL_NAME"
 	add_context_kernel_ok "$SESSION_NAME" "$CHANNEL_NAME" "callstack-user"
 
-	run_workload
+	run_workload $TEST_APP_USERSPACE
 
 	destroy_lttng_session_ok "$SESSION_NAME"
 
-	"$BABELTRACE_BIN" "$TRACE_PATH" | grep $EVENT_NAME | ./"$PARSE_CALLSTACK" --user "$TEST_APP" $USER_CS_EXPECTED
+	"$BABELTRACE_BIN" "$TRACE_PATH" | grep $EVENT_NAME | ./"$PARSE_CALLSTACK" --user "$TEST_APP_USERSPACE" $USER_CS_EXPECTED
 	ok $? "Validate userspace callstack"
 
 	rm -rf "$TRACE_PATH"
@@ -92,9 +94,22 @@ function test_kernel_callstack()
 {
 	TRACE_PATH=$(mktemp -d)
 	# Those are symbol expected to be present in the kernel callstack. This
-	# is not an exhaustive list since it's kernel depend.
-	KERNEL_CS_EXPECTED="save_stack_trace lttng_callstack_get_size lttng_event_reserve"
-	EVENT_NAME="gettid"
+	# is not an exhaustive list since it's kernel dependent.
+
+	# FIXME: we used to test for the following symbols as well:
+	# save_stack_trace, lttng_callstack_get_size, but they were removed
+	# because:
+	#	1. kernel commit 77072f09 make it so that save_stack_trace is
+	#	 omitted from the callstack itself, and
+	#
+	#	2. the code (of this commit) can trigger Tail Call Optimization
+	#	which mess up with the stacktrace by omiting the wrong address
+	#	from the stacktrace.
+	# When this is fixed, we should add both save_stack_trace and
+	# lttng_callstack_get_size symbols back in the list of expected
+	# addresses.
+	KERNEL_CS_EXPECTED="lttng_event_reserve"
+	EVENT_NAME="read"
 
 	diag "Kernel callstack test"
 	create_lttng_session_ok $SESSION_NAME "$TRACE_PATH"
@@ -103,7 +118,7 @@ function test_kernel_callstack()
 	lttng_enable_kernel_syscall_ok "$SESSION_NAME" "$EVENT_NAME" "$CHANNEL_NAME"
 	add_context_kernel_ok "$SESSION_NAME" "$CHANNEL_NAME" "callstack-kernel"
 
-	run_workload
+	run_workload $TEST_APP_KERNELSPACE
 
 	destroy_lttng_session_ok "$SESSION_NAME"
 
@@ -112,6 +127,15 @@ function test_kernel_callstack()
 
 	rm -rf "$TRACE_PATH"
 }
+
+# Only run userspace callstack test on x86
+uname -m | grep -E "x86" >/dev/null 2>&1
+if test $? == 0; then
+	NUM_TESTS=$((NUM_TESTS+11))
+	RUN_USERSPACE_TEST=1
+else
+	RUN_USERSPACE_TEST=0
+fi
 
 # MUST set TESTDIR before calling those functions
 plan_tests $NUM_TESTS
@@ -132,7 +156,10 @@ skip $isroot "Root access is needed. Skipping all tests." "$NUM_TESTS" ||
 	{
 		start_lttng_sessiond
 
-		test_user_callstack
+		if test $RUN_USERSPACE_TEST == 1; then
+			test_user_callstack
+		fi
+
 		test_kernel_callstack
 
 		stop_lttng_sessiond
