Tests: add kernel test into the `make check` test suite.
The Jenkins CI mostly run the `make check` suite. Only the Lava base CI
run the root_regression test suite. Most of those test can be run on
`make check` without incurring any major extra time.

Only `regression/tools/streaming/test_high_throughput_limits` is left in
root_regression since it is currently "unreasonable" in term of the time
it takes to run. This could be tackled another time.

Change-Id: I29d40fa8bec872bf2e22a8bd933f58fa6376ee22
Signed-off-by: Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>

diff --git a/tests/regression/kernel/test_ns_contexts_change b/tests/regression/kernel/test_ns_contexts_change
--- a/tests/regression/kernel/test_ns_contexts_change
+++ b/tests/regression/kernel/test_ns_contexts_change
@@ -131,7 +131,21 @@ function test_ns()
 		# Check that the events contain the right namespace inode number
 		validate_trace_count "${ns}_ns = $app_ns_inode" "$trace_path" 1
 		validate_trace_count "${ns}_ns = $app_unshare_ns_inode" "$trace_path" 1
+	else
+		touch "$file_sync_wait_before_unshare"
+
+		while [ ! -f "$file_sync_signal_after_unshare" ]; do
+			# Break if the app failed / died
+			if ! kill -0 "$app_pid" ; then
+				break
+				echo "# App failed"
+			fi
+			echo "# Waiting for app..."
+			sleep 0.5
+		done
+		touch "$file_sync_wait_after_unshare"
 	fi
+
 
 	# stop and destroy
 	destroy_lttng_session_ok "$session_name"
@@ -174,3 +188,4 @@ test_ns net
 #test_ns pid # pid_ns is special, can't be changed that way
 test_ns user
 test_ns uts
+set +x
