Support per UID buffers
This is a rather large commit. It adds the support for per UID buffers
for the user space tracer.

The --buffers-uid option is added to the lttng enable-channel command
which will set the session to use per UID buffers. So, all other channel
in that session MUST be set with the same buffer type or else an error
will be returned. For instance, here is an invalid use case:

$ lttng create
$ lttng enable-channel -u --buffers-uid chan1
$ lttng enable-channel -u chan2

The default is per PID (--buffers-pid). With no buffer type option, the
per PID is used for the UST tracer and global buffers for the kernel
being the only supported type for it (--buffers-global).

The tracing directory path are also changed to support this. For per UID
buffers, the path is now:

	~/lttng-traces/ust/uid/1000/64-bit/*

For per PID buffers:

	~/lttng-traces/<session_name>-<date>-<time>/ust/pid/ \
		<app-name>-<pid>-<date>-<time>/

So basically, for UID, traces are stored per UID/ABI and for PID is
simply stored with the app name and pid. The kernel traces are untouched
and are still in kernel/.

Tests are also added for per UID buffers.

Acked-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Signed-off-by: David Goulet <dgoulet@efficios.com>

diff --git a/tests/regression/ust/overlap/test_overlap b/tests/regression/ust/overlap/test_overlap
--- a/tests/regression/ust/overlap/test_overlap
+++ b/tests/regression/ust/overlap/test_overlap
@@ -30,7 +30,7 @@ NUM_DEMO1_2_EVENT=1
 NUM_DEMO2_EVENT=5
 NUM_DEMO3_EVENT=1
 
-NUM_TESTS=260
+NUM_TESTS=259
 
 source $TESTDIR/utils/utils.sh
 
@@ -301,13 +301,12 @@ test_enable_same_wildcard_filter_2()
 
 	enable_ust_lttng_event_filter $SESSION_NAME "$event_wild1" "1==1"
 
-	# Enabling the same events with same filters should fail
+	# Enabling the same events with same filters should fail. This one is expected to fail.
 	$TESTDIR/../src/bin/lttng/$LTTNG_BIN enable-event "$event_wild2" -s $SESSION_NAME -u --filter "1==1" >/dev/null 2>&1
-
-	if [ $? -eq 1 ]; then
+	if [ $? -ne 0 ]; then
 	    pass "Enable event $event_name with filtering for session $sess_name twice failure detected"
 	else
-	    fail "Enable event $event_name with filtering for session $sess_name twice failure detected"
+	    fail "Enable event $event_name with filtering for session $sess_name twice failure NOT detected"
 	fi
 
 	start_lttng_tracing $SESSION_NAME >/dev/null 2>&1
@@ -372,8 +371,6 @@ test_enable_same_event_filter()
 
 	enable_ust_lttng_event_filter $SESSION_NAME "$event_wild1" "1==1&&1==1"
 	enable_ust_lttng_event_filter $SESSION_NAME "$event_wild2" "1==1"
-
-	disable_ust_lttng_event $SESSION_NAME "ust*"
 
 	start_lttng_tracing $SESSION_NAME >/dev/null 2>&1
 
